kind: pipeline
name: build-centos6-nightly

steps:
- name: build-centos6-nightly
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: centos.6.nightly
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-centos6-stable

steps:
- name: build-centos6-stable
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: centos.6.stable
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-centos7-nightly

steps:
- name: build-centos7-nightly
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: centos.7.nightly
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-centos7-stable

steps:
- name: build-centos7-stable
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: centos.7.stable
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-ubuntu1604-nightly

steps:
- name: build-ubuntu1604-nightly
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: ubuntu.1604.nightly
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-ubuntu1604-stable

steps:
- name: build-ubuntu1604-stable
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: ubuntu.1604.stable
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-ubuntu1804-nightly

steps:
- name: build-ubuntu1804-nightly
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: ubuntu.1804.nightly
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
name: build-ubuntu1804-stable

steps:
- name: build-ubuntu1804-stable
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: ubuntu.1804.stable
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX .
  - docker push $DOCKER_NAME/useful-docker:$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

