kind: pipeline
name: useful_docker

steps:
- name: check_docker
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
    DOCKER_SUFFIX: centos.6.nightly
  commands:
  - echo $DOCKER_PASS | docker login -u $DOCKER_NAME --password-stdin
  - docker build --pull -t baiduxlab/useful-docker:$DOCKER_SUFFIX -f Dockerfile.$DOCKER_SUFFIX

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

