kind: pipeline
name: useful_docker

steps:
- name: check_docker
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  environment:
    DOCKER_NAME:
      from_secret: dockerhub_name
    DOCKER_PASS:
      from_secret: dockerhub_pass
  commands:
  - echo "$DOCKER_PASS"
  - echo "$DOCKER_NAME"
  - docker login -u "$DOCKER_NAME" -p "$DOCKER_PASS"
  - docker ps

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

